project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('planner/', include('planner.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = "core"


urlpatterns = [
    path("", views.home, name="home"),
    path('about/', views.about, name="about"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
]

urlpatterns += staticfiles_urlpatterns()

project/planner/urls.py
from django.urls import path
from . import views

app_name = "planner"

# Proyecto
urlpatterns = [
    path("", views.home, name="home"),
    path("proyecto/create/", views.ProyectoCreate.as_view(), name="proyecto_create"),
    path("proyecto/list/", views.ProyectoList.as_view(), name="proyecto_list"),
    path("proyecto/detail/<int:pk>", views.ProyectoDetail.as_view(), name="proyecto_detail"),
    path("proyecto/update/<int:pk>", views.ProyectoUpdate.as_view(), name="proyecto_update"),
    path("proyecto/delete/<int:pk>", views.ProyectoDelete.as_view(), name="proyecto_delete"),
]

# Tareas
urlpatterns += [
    path("tarea/list/", views.TareaList.as_view(), name="tarea_list"),
    path("tarea/create/", views.TareaCreate.as_view(), name="tarea_create"),
    path("tarea/detail/<int:pk>", views.TareaDetail.as_view(), name="tarea_detail"),
    path("tarea/update/<int:pk>", views.TareaUpdate.as_view(), name="tarea_update"),
    path("tarea/delete/<int:pk>", views.TareaDelete.as_view(), name="tarea_delete"),
]

urlpatterns += [
    path("responsable/list/", views.ResponsableList.as_view(), name="responsable_list"),
    path("responsable/update/<int:pk>", views.ResponsableUpdate.as_view(), name="responsable_update"),
    ]

project/core/models.py
from django.db import models

# Create your models here.

project/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2",]
        help_texts = {k: "" for k in fields}
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }

project/core/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from . import models
from .forms import CustomAuthenticationForm, CustomUserCreationForm


#@login_required
def home(request):
    return render(request, "core/index.html")

def about(request):
    return render(request, 'core/about.html')

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"


# @staff_member_required
def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "core/index.html", {"mensaje": "Usuario creado"})
    else:
        form = CustomUserCreationForm()
    return render(request, "core/register.html", {"form": form})

project/core/templates/core/components/calltoaction.html
<div class="card text-white bg-secondary my-5 py-4 text-center">
    <div class="card-body">
        <p class="text-white m-0">
            PlanApp: Simplifica tu planificación, maximiza tu productividad.
        </p>
    </div>
</div>

project/core/templates/core/components/card.html
<div class="col-md-6 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{ titulo }}</h2>
            <p class="card-text">{{ texto }}</p>
        </div>
        <div class="card-footer">
            <a class="btn btn-primary btn-sm" href={% url link %}>Ver lista</a>
        </div>
    </div>
</div>

project/core/templates/core/components/footer.html
<footer class="py-2 bg-dark fixed-bottom">
    <div class="container px-4 px-lg-5">
        <p class="m-0 text-center text-white">PlanApp - Proyecto Final CoderHouse - 2024</p>
    </div>
</footer>

project/core/templates/core/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'core:home' %}">PlanApp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link {% if request.path == "/" %} active {% endif %}" aria-current="page" href="{% url 'core:home' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == "/about" %} active {% endif %}" href="{% url 'core:about' %}">Acerca de mi</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link {% if request.path == "/planner/" %} active {% endif %}" href="{% url 'planner:home' %}">Planner</a></li>
                    <li class="nav-item"><a class="nav-link text-bg-info">{{ user.username }}</a></li>
                    <li class="nav-item">
                        <form action="{% url 'core:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-dark {{ fontsize }} ">Logout</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link {% if request.path == "/login/" %} active {% endif %}" href="{% url 'core:login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link {% if request.path == "/register/" %} active {% endif %}" href="{% url 'core:register' %}">Registrarse</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

project/core/templates/core/components/titulo1.html
<div class="row align-items-center my-5">
    <h1 class="pb-lg-3 text-white bg-primary px-3 py-2 rounded">
    {{ title }}
    </h1>
</div>