project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('planner/', include('planner.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = "core"


urlpatterns = [
    path("", views.home, name="home"),
    path('about/', views.about, name="about"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
]

urlpatterns += staticfiles_urlpatterns()

project/planner/urls.py
from django.urls import path
from . import views

app_name = "planner"

# Proyecto
urlpatterns = [
    path("", views.home, name="home"),
    path("proyecto/create/", views.ProyectoCreate.as_view(), name="proyecto_create"),
    path("proyecto/list/", views.ProyectoList.as_view(), name="proyecto_list"),
    path("proyecto/detail/<int:pk>", views.ProyectoDetail.as_view(), name="proyecto_detail"),
    path("proyecto/update/<int:pk>", views.ProyectoUpdate.as_view(), name="proyecto_update"),
    path("proyecto/delete/<int:pk>", views.ProyectoDelete.as_view(), name="proyecto_delete"),
]

# Tareas
urlpatterns += [
    path("tarea/list/", views.TareaList.as_view(), name="tarea_list"),
    path("tarea/create/", views.TareaCreate.as_view(), name="tarea_create"),
    path("tarea/detail/<int:pk>", views.TareaDetail.as_view(), name="tarea_detail"),
    path("tarea/update/<int:pk>", views.TareaUpdate.as_view(), name="tarea_update"),
    path("tarea/delete/<int:pk>", views.TareaDelete.as_view(), name="tarea_delete"),
]

urlpatterns += [
    path("responsable/list/", views.ResponsableList.as_view(), name="responsable_list"),
    path("responsable/update/<int:pk>", views.ResponsableUpdate.as_view(), name="responsable_update"),
    ]

project/planner/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
# class Estado(models.Model):
#     estado = models.CharField(max_length=50, unique=True)
    
#     def __str__(self) -> str:
#         return self.estado

class Proyecto(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    descripcion = models.CharField(max_length=250, null=True, blank=True, verbose_name="descripción")
    fecha_inicio = models.DateField(null=True, blank=True, default=timezone.now)
    fecha_fin = models.DateField(null=True, blank=True, default=timezone.now)
    responsable = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='proyectos_responsable')
    
    @property
    def avance(self):
        total_tareas = self.related_tareas.count()
        if total_tareas == 0:
            return 0
        tareas_completadas = self.related_tareas.filter(completada=True).count()
        return (tareas_completadas / total_tareas) * 100
    
    def __str__(self) -> str:
        """Representa una instancia del modelo como una cadena de texto"""
        return self.nombre

class Tarea(models.Model):
    nombre = models.CharField(max_length=200)
    completada = models.BooleanField(default=False)
    proyecto = models.ForeignKey(Proyecto, related_name='related_tareas', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self) -> str:
        return self.nombre

class Responsable(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    avatar = models.ImageField(upload_to='avatars', null=True, blank=True)

    def __str__(self):
        return f'{self.nombre} {self.apellido} ({self.user.get_username})'

project/planner/forms.py
from django import forms
from django.forms.models import modelformset_factory
from . import models

class ProyectoForm(forms.ModelForm):
    class Meta:
        model = models.Proyecto
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
            "fecha_inicio": forms.DateInput(attrs={"class": "form-control"}),
            "fecha_fin": forms.DateInput(attrs={"class": "form-control"}),
        }

class TareaForm(forms.ModelForm):
    class Meta:
        model = models.Tarea
        fields = "__all__"

class ResponsableForm(forms.ModelForm):
    class Meta:
        model = models.Responsable
        fields = "__all__"
        widgets = {
            "avatar": forms.ClearableFileInput(attrs={"class": "form-control"}),
        }

project/planner/views.py
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from . import forms, models

@login_required
def home(request):
    # return render(request, "planner/index.html")

    # proyectos = models.Proyecto.objects.all()
    # proyectos_data = []

    # for proyecto in proyectos:
    #     total_tareas = proyecto.tareas.count()
    #     tareas_completadas = proyecto.tareas.filter(completada=True).count()
    #     tareas_no_completadas = total_tareas - tareas_completadas
    #     proyectos_data.append({
    #         'nombre': proyecto.nombre,
    #         'total_tareas': total_tareas,
    #         'tareas_completadas': tareas_completadas,
    #         'tareas_no_completadas': tareas_no_completadas,
    #     })

    # context = {
    #     'proyectos_data': proyectos_data,
    # }
    return render(request, 'planner/index.html') #context)


# *** TareaCATEOGORIA

# LIST
# def Proyecto_list(request):
#     consulta = request.GET.get("consulta", None)
#     if consulta:
#         print(consulta)
#         query = models.Proyecto.objects.filter(nombre__icontains=consulta)
#     else:
#         query = models.Proyecto.objects.all()
#     context = {"Tareas": query}
#     return render(request, "Tarea/Proyecto_list.html", context)


class ProyectoList(ListView, LoginRequiredMixin):
    model = models.Proyecto

    # context_object_name = "Tareas"
    # template_name = "Tarea/Proyecto___list.html"

    def get_queryset(self) -> QuerySet:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Proyecto.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Proyecto.objects.all()
        return object_list

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     consulta = self.request.GET.get("consulta")
    #     if consulta:
    #         queryset = queryset.filter(Q(nombre__icontains=consulta) | Q(descripcion__icontains=consulta))
    #     return queryset


# CREATE
# def Proyecto_create(request):
#     if request.method == "POST":
#         form = forms.ProyectoForm(request.POST)
#         if form.is_valid:
#             form.save()
#             return redirect("Tarea:home")
#     else:  # request.method == "GET"
#         form = forms.ProyectoForm()
#     return render(request, "Tarea/Proyecto_create.html", context={"form": form})


class ProyectoCreate(CreateView, LoginRequiredMixin):
    model = models.Proyecto
    form_class = forms.ProyectoForm
    success_url = reverse_lazy("planner:home")

    # def get_context_data(self, **kwargs):
    #     data = super().get_context_data(**kwargs)
    #     if self.request.POST:
    #         data['formset'] = forms.TareaFormSet(self.request.POST)
    #     else:
    #         data['formset'] = forms.TareaFormSet(queryset=models.Tarea.objects.none())
    #     return data

    # def form_valid(self, form):
    #     context = self.get_context_data()
    #     formset = context['formset']
    #     if formset.is_valid():
    #         self.object = form.save(commit=False)  # Guardar el proyecto sin confirmarlo aún
    #         tareas = formset.save(commit=False)  # Guardar las tareas sin confirmarlas aún
    #         self.object.save()  # Ahora guardar el proyecto para obtener el ID
    #         for tarea in tareas:
    #             tarea.proyecto = self.object  # Asignar el proyecto a cada tarea
    #             tarea.save()  # Guardar la tarea con la relación al proyecto
    #         return redirect(self.get_success_url())
    #     else:
    #         return self.form_invalid(form)


# UPDATE
# def Proyecto_update(request, pk: int):
#     query = models.Proyecto.objects.get(id=pk)
#     if request.method == "POST":
#         form = forms.ProyectoForm(request.POST, instance=query)
#         if form.is_valid:
#             form.save()
#             return redirect("Tarea:Proyecto_list")
#     else:  # request.method == "GET"
#         form = forms.ProyectoForm(instance=query)
#     return render(request, "Tarea/Proyecto_update.html", context={"form": form})


class ProyectoUpdate(UpdateView, LoginRequiredMixin):
    model = models.Proyecto
    form_class = forms.ProyectoForm
    success_url = reverse_lazy("planner:proyecto_list")

    # def get_context_data(self, **kwargs):
    #     data = super().get_context_data(**kwargs)
    #     if self.request.POST:
    #         data['formset'] = forms.TareaFormSet(self.request.POST, instance=self.object)
    #     else:
    #         data['formset'] = forms.TareaFormSet(queryset=models.Tarea.objects.filter(proyecto=self.object))
    #     return data

    # def form_valid(self, form):
    #     context = self.get_context_data()
    #     formset = context['formset']
    #     if formset.is_valid():
    #         self.object = form.save(commit=False)  # Guardar el proyecto sin confirmarlo aún
    #         tareas = formset.save(commit=False)  # Guardar las tareas sin confirmarlas aún
    #         self.object.save()  # Ahora guardar el proyecto para obtener el ID
    #         for tarea in tareas:
    #             tarea.proyecto = self.object  # Asignar el proyecto a cada tarea
    #             tarea.save()  # Guardar la tarea con la relación al proyecto
    #         return redirect(self.get_success_url())
    #     else:
    #         return self.form_invalid(form)


# DETAIL
# def Proyecto_detail(request, pk: int):
#     query = models.Proyecto.objects.get(id=pk)
#     return render(request, "Tarea/Proyecto_detail.html", {"Tarea": query})


class ProyectoDetail(DetailView, LoginRequiredMixin):
    model = models.Proyecto
    # context_object_name = "Tarea"


# DELETE
# def Proyecto_delete(request, pk: int):
#     query = models.Proyecto.objects.get(id=pk)
#     if request.method == "POST":
#         query.delete()
#         return redirect("Tarea:Proyecto_list")
#     return render(request, "Tarea/Proyecto_delete.html", context={"Tarea": query})


class ProyectoDelete(LoginRequiredMixin, DeleteView):
    model = models.Proyecto
    # template_name = "Tarea/Proyecto_delete.html"
    success_url = reverse_lazy("planner:proyecto_list")


# *** Tarea


class TareaList(ListView, LoginRequiredMixin):
    model = models.Tarea

    def get_queryset(self) -> QuerySet:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Tarea.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Tarea.objects.all()
        return object_list


class TareaCreate(CreateView, LoginRequiredMixin):
    model = models.Tarea
    form_class = forms.TareaForm
    # proyecto = models.Tarea.proyecto
    success_url = reverse_lazy("planner:home")


class TareaUpdate(UpdateView, LoginRequiredMixin):
    model = models.Tarea
    form_class = forms.TareaForm
    success_url = reverse_lazy("planner:tarea_list")


class TareaDetail(DetailView, LoginRequiredMixin):
    model = models.Tarea


class TareaDelete(LoginRequiredMixin, DeleteView):
    model = models.Tarea
    success_url = reverse_lazy("planner:tarea_list")

class ResponsableUpdate(LoginRequiredMixin, UpdateView):
    model = models.Responsable
    form_class = forms.ResponsableForm
    success_url = reverse_lazy("planner:responsable_list")

class ResponsableList(ListView, LoginRequiredMixin):
    model = models.Responsable

    def get_queryset(self) -> QuerySet:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Responsable.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Responsable.objects.all()
        return object_list

project/planner/templates/planner/index.html
{% extends 'core/base.html' %}
{% block titulo %}
    App Planner
{% endblock titulo %}
{% block contenido %}
<div class="container my-5">
  <div class="row">
    <div class="col">
      <h3 class="pb-3 border-bottom">Proyectos</h3>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-primary me-md-2" href="{% url 'planner:proyecto_create' %}" role="button">Crear Proyecto</a>
        <a class="btn btn-outline-primary" href="{% url 'planner:proyecto_list' %}" role="button">Listar Proyectos</a>
      </div>
    </div>
    <div class="col">
      <h3 class="pb-3 border-bottom">Tareas</h3>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-success me-md-2" href="{% url 'planner:tarea_create' %}" role="button">Crear Tarea</a>
        <a class="btn btn-outline-success" href="{% url 'planner:tarea_list' %}" role="button">Listar Tareas</a>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h3 class="pb-3 border-bottom">Responsables</h3>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-success me-md-2" href="{% url 'planner:responsable_list' %}" role="button">Editar Responsables</a>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 my-5">
    <a class="btn btn-secondary" href="{% url 'core:home' %}" role="button">Ir a Inicio</a>
    </div>
  </div>
</div>

{% endblock contenido %}

project/planner/templates/planner/proyecto_confirm_delete.html
{% extends 'core/base.html' %}

{% block titulo %}
    Planner: Borrar un Proyecto
{% endblock titulo %}

{% block contenido %}
    
    <p class="fs-5 fst-italic">¿Confirma eliminar "{{ object.nombre }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'planner:home' %}">Volver al inicio de Planner</a>
    </div>

{% endblock contenido %}

project/planner/templates/planner/proyecto_detail.html
{% extends 'core/base.html' %}
{% comment  %}

{% block titulo %}
    Planner: Detalle de un Proyecto
{% endblock titulo %}

{% block contenido %}

    <ul>
        <li>Nombre: {{ object.nombre }}</li>
        <li>Descripción: {{ object.descripcion }}</li>
    </ul>

    <div class="fs-3 pb-4">
        <a href="{% url 'planner:proyecto_list' %}">Volver</a>
    </div>

{% endblock contenido %}
{% endcomment %}

{% block titulo %}
    Planner: Detalle de Proyecto
{% endblock titulo %}
{% block contenido %}
    <div class="container my-5">
        <div class="py-4">
            <form class="input-group mb-3"
                  action="{% url 'planner:proyecto_list' %}"
                  method="get">
                <input type="text"
                       class="form-control"
                       name="consulta"
                       placeholder="Buscar..."
                       aria-label="Buscar">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
            </form>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Proyecto</th>
                    <th scope="col">Descripción</th>
                    <th scope="col">Inicio</th>
                    <th scope="col">Fin</th>
                    <th scope="col">Responsable</th>
                    <th scope="col">Avance</th>
                </tr>
            </thead>
            <tbody>
                    <tr>
                        <td>{{ object.nombre }}</td>
                        <td>{{ object.descripcion }}</td>
                        <td>{{ object.fecha_inicio }}</td>
                        <td>{{ object.fecha_fin }}</td>
                        <td>{{ object.responsable }}</td>
                        <td>{{ object.avance }}%</td>
                    </tr>
            </tbody>
        </table>
        <div class="fs-3 pb-4">
            <a class="btn btn-secondary"
               href="{% url 'planner:proyecto_list' %}"
               role="button">Volver</a>
        </div>
    </div>
{% endblock contenido %}

project/planner/templates/planner/proyecto_form.html
{% extends 'core/base.html' %}

{% block titulo %}
    Tarea: 
    {% if form.instance.pk %}
        Editar
    {% else %}
        Crear
    {% endif %}
    Proyecto
{% endblock titulo %}

{% block contenido %}
    
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="button" id="add-tareas-btn" class="btn btn-secondary">Añadir Tareas</button>
            <div id="tareas-formset" style="display: none;">
            {{ formset.management_form }}
            {% for form in formset %}
                {{ form.as_table }}
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'planner:home' %}">Volver al inicio de Planner</a>
    </div>

    <script>
        document.getElementById('add-tareas-btn').addEventListener('click', function() {
            var tareasFormset = document.getElementById('tareas-formset');
            if (tareasFormset.style.display === 'none') {
                tareasFormset.style.display = 'block';
            } else {
                tareasFormset.style.display = 'none';
            }
        });
    </script>

{% endblock contenido %}

project/planner/templates/planner/proyecto_list.html
{% extends 'core/base.html' %}
{% block titulo %}
    Planner: Lista de Proyectos
{% endblock titulo %}
{% block contenido %}
    <div class="container my-5">
        <div class="py-4">
            <form class="input-group mb-3"
                  action="{% url 'planner:proyecto_list' %}"
                  method="get">
                <input type="text"
                       class="form-control"
                       name="consulta"
                       placeholder="Buscar..."
                       aria-label="Buscar">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
            </form>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Proyecto</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for proyecto in object_list %}
                    <tr>
                        <td>{{ proyecto.nombre }}</td>
                        <td>
                            <a class="btn btn-info btn-sm me-1"
                               href="{% url 'planner:proyecto_detail' proyecto.id %}">Detalle</a>
                            <a class="btn btn-warning btn-sm me-1"
                               href="{% url 'planner:proyecto_update' proyecto.id %}">Cambiar</a>
                            <a class="btn btn-danger btn-sm"
                               href="{% url 'planner:proyecto_delete' proyecto.id %}">Borrar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="mt-4">
            <a class="btn btn-secondary"
               href="{% url 'planner:home' %}"
               role="button">Volver al inicio de Planner</a>
        </div>
    </div>
{% endblock contenido %}

project/planner/templates/planner/proyecto_update.html
{% extends 'core/base.html' %}

{% block titulo %}
    Planner: Modificar un Proyecto
{% endblock titulo %}

{% block contenido %}
    
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'planner:proyecto_list' %}">Volver</a>
    </div>

{% endblock contenido %}

project/planner/templates/planner/responsable_form.html
{% extends 'core/base.html' %}

{% block titulo %}
    Planner: Modificar un Responsable
{% endblock titulo %}

{% block contenido %}
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_p }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'planner:responsable_list' %}">Volver</a>
    </div>

{% endblock contenido %}

project/planner/templates/planner/responsable_list.html
{% extends 'core/base.html' %}
{% block titulo %}
    Planner: Lista de Responsables
{% endblock titulo %}
{% block contenido %}
    <div class="container my-5">
        <div class="py-4">
            <form class="input-group mb-3"
                  action="{% url 'planner:responsable_list' %}"
                  method="get">
                <input type="text"
                       class="form-control"
                       name="consulta"
                       placeholder="Buscar..."
                       aria-label="Buscar">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
            </form>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Avatar</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Usuario</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for responsable in object_list %}
                    <tr>
                        <td>{% if responsable.avatar %}
                            <img src="{{ responsable.avatar.url }}" alt="" width="80" height="80">
                            {% else %}
                            No image
                            {% endif %}</td>
                        
                        <td>{{ responsable.nombre }}</td>
                        <td>{{ responsable.apellido }}</td>
                        <td>{{ responsable.user }}</td>
                        <td>
                        <a class="btn btn-warning btn-sm me-1"
                               href="{% url 'planner:responsable_update' responsable.id %}">Cambiar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="mt-4">
            <a class="btn btn-secondary"
               href="{% url 'planner:home' %}"
               role="button">Volver al inicio de Planner</a>
        </div>
    </div>
{% endblock contenido %}

project/planner/templates/planner/tarea_confirm_delete.html
{% extends 'core/base.html' %}

{% block titulo %}
    Planner: Borrar una Tarea
{% endblock titulo %}

{% block contenido %}
    
    <p class="fs-5 fst-italic">¿Confirma eliminar "{{ object.nombre }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'planner:home' %}">Volver al inicio de Planner</a>
    </div>

{% endblock contenido %}

project/planner/templates/planner/tarea_detail.html
{% extends 'core/base.html' %}
{% block titulo %}
    Planner: Detalle de Tarea
{% endblock titulo %}

{% block contenido %}

    <ul>
        <li>Nombre: {{ object.nombre }}</li>
    </ul>

    <div class="fs-3 pb-4">
        <a class="btn btn-secondary"
               href="{% url 'planner:tarea_list' %}"
               role="button">Volver</a>
    </div>

{% endblock contenido %}

project/planner/templates/planner/tarea_form.html
{% extends 'core/base.html' %}

{% block titulo %}
    Tarea: 
    {% if form.instance.pk %}
        Editar
    {% else %}
        Crear
    {% endif %}
    Tareas
{% endblock titulo %}

{% block contenido %}
    
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'planner:home' %}">Volver al inicio de Planner</a>
    </div>

{% endblock contenido %}

project/planner/templates/planner/tarea_list.html
{% extends 'core/base.html' %}
{% block titulo %}
    Planner: Lista de Tareas
{% endblock titulo %}
{% block contenido %}
    <div class="container my-5">
        <div class="py-4">
            <form class="input-group mb-3"
                  action="{% url 'planner:tarea_list' %}"
                  method="get">
                <input type="text"
                       class="form-control"
                       name="consulta"
                       placeholder="Buscar..."
                       aria-label="Buscar">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
            </form>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Tareas</th>
                    <th scope="col">Completada</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for tarea in object_list %}
                    <tr>
                        <td>{{ tarea.nombre }}</td>
                        <td>{% if tarea.completada %}
                            Si
                            {% else %}
                            No
                        {% endif %}
                        </td>
                        <td>
                            <a class="btn btn-info btn-sm me-1"
                               href="{% url 'planner:tarea_detail' tarea.id %}">Detalle</a>
                            <a class="btn btn-warning btn-sm me-1"
                               href="{% url 'planner:tarea_update' tarea.id %}">Cambiar</a>
                            <a class="btn btn-danger btn-sm"
                               href="{% url 'planner:tarea_delete' tarea.id %}">Borrar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="mt-4">
            <a class="btn btn-secondary"
               href="{% url 'planner:home' %}"
               role="button">Volver al inicio de Planner</a>
        </div>
    </div>
{% endblock contenido %}

project/planner/templates/planner/tareas_detail.html
{% extends 'core/base.html' %}
{% block titulo %}
    Planner: Detalle de Tarea
{% endblock titulo %}

{% block contenido %}

    <ul>
        <li>Nombre: {{ object.nombre }}</li>
    </ul>

    <div class="fs-3 pb-4">
        <a href="{% url 'planner:tareas_list' %}">Volver</a>
    </div>

{% endblock contenido %}

project/planner/templates/planner/tareas_form.html
{% extends 'core/base.html' %}

{% block titulo %}
    Tarea: 
    {% if form.instance.pk %}
        Editar
    {% else %}
        Crear
    {% endif %}
    Tareas
{% endblock titulo %}

{% block contenido %}
    
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'producto:home' %}">Volver al inicio de Tareas</a>
    </div>

{% endblock contenido %}